blogapp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

blogapp/main/routes.py
from flask import render_template, request, Blueprint, redirect, url_for
from blogapp.models import Post, Amount, Choice
from blogapp.main.forms import ProfileForm, DebitCreditForm
from blogapp import db

main = Blueprint('main',__name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', title='Home Title', posts=posts)

@main.route('/funds', methods=['GET', 'POST'])
def funds():
    form = ProfileForm()

    if form.validate_on_submit():
        if form.debitcredit.data:
            return redirect(url_for('main.debitcredit'))
        if form.statement.data:
            return redirect(url_for('main.statement'))

    return render_template('fund.html', title='Funds', form=form)

@main.route('/debitcredit', methods=['GET', 'POST'])
def debitcredit():

    form = DebitCreditForm()
    balance = 0
    amount = Amount.query.all()
    for amt in amount:
        balance = amt.balance
        print(amt.date_created)
        print(amt.category)
        print(amt.camount)
        print(amt.damount)
        print(amt.balance)

    #if form.validate_on_submit():
    if request.method == 'POST':
        print ('working')
        print (balance)
        if form.debit.data:
            cat = form.option.data
            amt = int(form.amount.data)
            balance = balance - int(form.amount.data)
            amount = Amount(category=cat, camount=0, damount=amt, balance=balance)
            db.session.add(amount)
            db.session.commit()

        if form.credit.data:
            cat = form.option.data
            amt = int(form.amount.data)
            print (balance)
            print (int(form.amount.data))
            balance = balance + int(form.amount.data)
            print (balance)
            amount = Amount(category=cat, camount=amt, damount=0, balance=balance)
            db.session.add(amount)
            db.session.commit()

    return render_template('debitcredit.html', form=form, balance = balance, title='Transactions')

@main.route('/statement', methods=['GET', 'POST'])
def statement():

    #form = StatementForm()
    statement = Amount.query.all()

    for tranamt in statement:
        tranbalance = tranamt.balance

    return render_template('statement.html', statement=statement, tranbalance = tranbalance, title='Statments')

@main.route('/choices')
def choices():
    opt = Choice.query.all()
    list_choices = [r.as_dict() for r in opt]
    return jsonify(list_choices)

@main.route('/about')
def about():
    return render_template('about.html', title='About Title')

blogapp/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from blogapp import db
from blogapp.models import Post
from blogapp.posts.forms import PostForm

posts = Blueprint('posts',__name__)





@posts.route('/post/new', methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your Post has been added to the blog', 'success')
        return redirect(url_for('main.home'))

    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title,post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title =  form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your Post has been updated!!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your Post has been deleted!!', 'success')
    return redirect(url_for('main.home'))

blogapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blogapp import db, bcrypt
from blogapp.models import User, Post
from blogapp.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestRestForm, ResetPasswordForm)
from blogapp.users.utils import save_picture, send_reset_email
users = Blueprint('users',__name__)



@users.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your Account has been Created! You can able to Log in now','success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Resgister', form=form)


@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user,remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Un-successfull. Please check the Credentials','danger')
    return render_template('login.html', title='Login', form=form)

# print (__name__)
# print(__main__)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your Account has been Updated','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pic/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestRestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to register mailbox with instructions to reset your password.','info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expird token','warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your Password t has been Updated! You can able to Log in now','success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

blogapp/templates/about.html
{% extends 'base.html' %}
{% block content %}
      <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <h5> This is About Page </h5>
        </div>
       </div>
      </article>

{% endblock content %}

blogapp/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

blogapp/templates/base.html
<!doctype html>

<html>

<head>

      <!-- Required meta tags -->

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


      <!-- Bootstrap CSS -->

      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">

      {% if title %}
        <title> {{ title }} </title>
      {% else %}
        <title> Default Title </title>
      {% endif %}
</head>
<body>
  <!--Navigation-->

  <header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
    <a class="navbar-brand mr-4" href="/">Society</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('main.home')}}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Funds
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('main.debitcredit')}}">Manage Account</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('main.statement')}}">Statements</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about')}}">About</a>
        </li>
      </ul>

        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{url_for('posts.new_post')}}">New Post</a>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{current_user.username}}</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{{url_for('users.account')}}">My Profile</a>
                  <a class="dropdown-item" href="{{url_for('users.logout')}}">Logout</a>
                </div>
            </li>
          {% else %}
            <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
            <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{category}}">
              {{message}}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %}{% endblock content%}
    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Society Announcements</h3>
        <p class='text-muted'>
          <ul class="list-group">
            <a href="#"><li class="list-group-item list-group-item-light">Charity Events</li></a>
            <a href="#"><li class="list-group-item list-group-item-light">Sports calendar</li></a>
            <a href="#"><li class="list-group-item list-group-item-light">Kids Zone</li></a>
            <a href="#"><li class="list-group-item list-group-item-light">Recreation</li></a>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>

     <!--Optional JavaScript -->
     <!-- jQuery first, then Popper.js, then Bootstrap JS -->


      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>

</html>

blogapp/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4"> {{legend}} </legend>

          <div class="form-group">
            {{ form.title.label(class="form-control-label") }}

            {% if form.title.errors %}
              {{ form.title(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                  {% for error in form.title.errors %}
                    <span> {{error}}</span>
                  {% endfor %}
                </div>
            {% else %}
              {{ form.title(class="form-control form-control-lg") }}
            {% endif %}

          </div>

          <div class="form-group">
            {{ form.content.label(class="form-control-label") }}

            {% if form.content.errors %}
              {{ form.content(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                  {% for error in form.content.errors %}
                    <span> {{error}}</span>
                  {% endfor %}
                </div>
            {% else %}
              {{ form.content(class="form-control form-control-lg") }}
            {% endif %}
          </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary mb-2") }}
      </div>
    </form>
  </div>

{% endblock content %}

blogapp/templates/debitcredit.html
{% extends "base.html" %}
{% block content %}
{% import "bootstrap/wtf.html" as wtf %}

<link rel="stylesheet" type = "text/css" href="{{url_for('static', filename='base1.css')}}">


<div class="manage">
  <h1 style="color: #060c38"> Manage Account. </h1>
</div>

<div class="container-fluid manage1">
    <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <form method="POST">
                {# This hidden_tag is a CSRF security feature. #}
                {{ form.hidden_tag() }}
                <div class="form-group  required"><label class="control-label" for="option"></label>
                    <input class="form-control" id="option" name="option" placeholder="Type Here" required type="text" value="">
                </div>
                <div class="form-group "><label class="control-label" for="amount">Amount</label>
                    <input class="form-control" id="amount" name="amount" type="text" value="">
                </div>
                <input class="btn btn-secondary" id="debit" name="debit" type="submit" value="Debit">
                <input class="btn btn-secondary" id="credit" name="credit" type="submit" value="Credit">
              </form>
            </div>
          </div>
        </div>
        <br></br>
      <div class="balance" style="font-size: 30px;">
        <p> Account Balance: {{balance}}</P>
      </div>

{% endblock content %}

blogapp/templates/fund.html
{% extends "base.html" %}
{% block content %}
{% import "bootstrap/wtf.html" as wtf %}

<div class="prof">
  <h1 style="color: #060c38"> SB Royal Apartments. </h1>
</div>

<div class="container-fluid prof1">
<div class="row">
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <form method="POST" class="form-container">
            {# This hidden_tag is a CSRF security feature. #}
            {{ form.hidden_tag() }}
            {{ wtf.form_field(form.debitcredit) }} <br/> <br/>
            {{ wtf.form_field(form.statement) }}
        </form>
    </div>
</div>
</div>

{% endblock %}

blogapp/templates/home.html
{% extends "base.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{url_for('posts.post', post_id=post.id)}}">{{post.title}}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num}}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num)}}">{{ page_num}}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

blogapp/templates/login.html
{% extends 'base.html' %}
{% block content %}
      <div class="content-section">
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Log In </legend>

              <div class="form-group">
                {{ form.email.label(class="form-control-label") }}

                {% if form.email.errors %}
                  {{ form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                        <span> {{error}}</span>
                      {% endfor %}
                    </div>
                {% else %}
                  {{ form.email(class="form-control form-control-lg") }}
                {% endif %}

              </div>

              <div class="form-group">
                {{ form.password.label(class="form-control-label") }}

                {% if form.password.errors %}
                  {{ form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                      {% for error in form.password.errors %}
                        <span> {{error}}</span>
                      {% endfor %}
                    </div>
                {% else %}
                  {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
              </div>
              <div class="form-check">
                {{ form.remember(class="form-check-input")}}
                {{ form.remember.label(class="form-check-label")}}
              </div>
          </fieldset>
          <div class="form-group">
            {{ form.submit(class="btn btn-primary mb-2") }}
            <small class="text-muted ml-2">
              <a href="{{ url_for('users.reset_request')}}"> Forgot Password? </a>
            </small>
          </div>

        </form>
      </div>
      <div class="border-top pt-3">
        <small class="text-muted">
          Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}"> Sign Up Now </a>
        </small>
      </div>

{% endblock content %}

blogapp/templates/post.html
{% extends "base.html" %}
{% block content %}
        <article class="media content-section">
        <!-- <div class="shadow-lg p-3 mb-5 bg-white rounded"> -->
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              {% if post.author == current_user %}
                <div>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post', post_id=post.id)}}">Update </a>
                  <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                    Delete
                  </button>
                </div>
              {% endif %}
            </div>
            <h2 class="article-title">{{post.title}}</h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post',post_id=post.id)}}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Delete">
                </form>
              </div>
            </div>
          </div>
        </div>
{% endblock content %}

blogapp/templates/register.html
{% extends 'base.html' %}
{% block content %}
      <div class="content-section">
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Join Today </legend>
              <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                  {{ form.username(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                      {% for error in form.username.errors %}
                        <span> {{error}}</span>
                      {% endfor %}
                    </div>
                {% else %}
                  {{ form.username(class="form-control form-control-lg") }}
                {% endif %}

              </div>

              <div class="form-group">
                {{ form.email.label(class="form-control-label") }}

                {% if form.email.errors %}
                  {{ form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                        <span> {{error}}</span>
                      {% endfor %}
                    </div>
                {% else %}
                  {{ form.email(class="form-control form-control-lg") }}
                {% endif %}

              </div>

              <div class="form-group">
                {{ form.password.label(class="form-control-label") }}

                {% if form.password.errors %}
                  {{ form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                      {% for error in form.password.errors %}
                        <span> {{error}}</span>
                      {% endfor %}
                    </div>
                {% else %}
                  {{ form.password(class="form-control form-control-lg") }}
                {% endif %}


              </div>

              <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}

                {% if form.confirm_password.errors %}
                  {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                      {% for error in form.confirm_password.errors %}
                        <span> {{error}}</span>
                      {% endfor %}
                    </div>
                {% else %}
                  {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}

              </div>
          </fieldset>
          <div class="form-group">
            {{ form.submit(class="btn btn-primary mb-2") }}
          </div>
        </form>
      </div>
      <div class="border-top pt-3">
        <small class="text-muted">
          Already Have an Account? <a class="ml-2" href="{{ url_for('users.login') }}"> Sign In </a>
        </small>
      </div>

{% endblock content %}

blogapp/templates/user_posts.html
{% extends "base.html" %}
{% block content %}
  <h1 class="mb-3"> Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{url_for('posts.post', post_id=post.id)}}">{{post.title}}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num)}}">{{ page_num}}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts',username=user.username, page=page_num)}}">{{ page_num}}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}